### ISSUE TITLE
Thing getPixTeam isn't defined in code and maybe wrong call some funсtion

### ISSUE THREAD

**Issue by rpisarev** [aleshkashell/googleAdmin#2]
1. Thing getPixTeam isn't defined in code. Please, fix function updateAllUserPost()
2. result = updateInformation(adminEmail=adminEmail, userEmail=email, post=post, department=department)
But, def updateInformation(userEmail, post, department, telephone)

So it calls incorrectly

**Comment by aleshkashell** [comment]
updateAllUserPost() was used for internal things. Fix.
